import { Translation, ProjectItem, Language } from './types';
import { HardHat, Truck, ShieldCheck, ClipboardList, Users, Forklift } from 'lucide-react';

export const TRANSLATIONS: Record<Language, Translation> = {
  he: {
    nav_home: 'בית',
    nav_about: 'אודות',
    nav_services: 'שירותים',
    nav_projects: 'פרויקטים',
    nav_contact: 'צור קשר',
    hero_title: 'א. מעלה השחר',
    hero_subtitle: 'מובילים בכוח אדם לענף הבנייה - שירות, בטיחות ואמינות',
    hero_cta: 'שלח קורות חיים',
    about_title: 'אודות החברה',
    about_desc: 'חברת א.מעלה השחר מספקת כוח אדם מקצועי לענף הבנייה בכל הארץ תוך הקפדה על שירות, בטיחות ואמינות. אנו מתמחים באספקת צוותים מיומנים לפרויקטים מורכבים.',
    services_title: 'השירותים שלנו',
    projects_title: 'לקוחות ופרויקטים',
    why_us_title: 'למה לבחור בנו?',
    contact_title: 'שלח קו״ח',
    contact_name: 'שם מלא',
    contact_email: 'אימייל',
    contact_phone: 'טלפון',
    contact_city: 'עיר מגורים',
    contact_cv: 'קורות חיים (PDF/Word)',
    contact_submit: 'שליחה',
    contact_info_title: 'פרטי התקשרות',
    footer_rights: '© 2025 א.מעלה השחר שירותי כוח אדם בע"מ',
    
    // Accessibility
    access_title: 'נגישות',
    accessibility: 'נגישות',
    accessibilityTools: 'כלי נגישות',
    customizeYourExperience: 'התאם את חווית הגלישה שלך',
    textSize: 'גודל טקסט',
    colorModes: 'מצבי צבע',
    grayscale: 'גווני אפור',
    invertColors: 'היפוך צבעים',
    lowSaturation: 'רוויה נמוכה',
    colorBlindFilter: 'פילטר עיוורון צבעים',
    none: 'ללא',
    redGreen: 'אדום/ירוק (Deuteranopia)',
    red: 'אדום (Protanopia)',
    blueYellow: 'כחול/צהוב (Tritanopia)',
    visualOptions: 'אפשרויות תצוגה',
    highContrast: 'ניגודיות גבוהה',
    largeText: 'טקסט גדול',
    highlightLinks: 'הדגשת קישורים',
    underlineLinks: 'קו תחתון לקישורים',
    hideImages: 'הסתרת תמונות',
    textOptions: 'אפשרויות טקסט',
    readableFont: 'גופן קריא',
    increaseLineSpacing: 'הגדלת מרווח שורות',
    letterSpacing: 'מרווח בין אותיות',
    textAlignment: 'יישור טקסט',
    navigationOptions: 'אפשרויות ניווט',
    largeCursor: 'סמן גדול',
    reduceMotion: 'הפחתת תנועה',
    stopAnimations: 'עצירת אנימציות',
    resetToDefault: 'אפס לברירת מחדל',
    needHelp: 'צריך עזרה?',
    viewFullStatement: 'הצהרת נגישות מלאה'
  },
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'من نحن',
    nav_services: 'خدماتنا',
    nav_projects: 'مشاريعنا',
    nav_contact: 'اتصل بنا',
    hero_title: 'أ. معاليه هشاحر',
    hero_subtitle: 'رواد القوى العاملة في قطاع البناء - خدمة، أمان وموثوقية',
    hero_cta: 'أرسل سيرتك الذاتية',
    about_title: 'عن الشركة',
    about_desc: 'توفر شركة أ. معاليه هشاحر قوى عاملة محترفة لقطاع البناء في جميع أنحاء البلاد مع التركيز على الخدمة والسلامة والموثوقية.',
    services_title: 'خدماتنا',
    projects_title: 'عملاء ومشاريع',
    why_us_title: 'لماذا تختارنا؟',
    contact_title: 'أرسل السيرة الذاتية',
    contact_name: 'الاسم الكامل',
    contact_email: 'البريد الإلكتروني',
    contact_phone: 'الهاتف',
    contact_city: 'المدينة',
    contact_cv: 'السيرة الذاتية',
    contact_submit: 'إرسال',
    contact_info_title: 'معلومات الاتصال',
    footer_rights: '© 2025 أ. معاليه هشاحر لخدمات القوى العاملة م.ض',
    
    // Accessibility
    access_title: 'سهولة الوصول',
    accessibility: 'سهولة الوصول',
    accessibilityTools: 'أدوات الوصول',
    customizeYourExperience: 'تخصيص تجربتك',
    textSize: 'حجم النص',
    colorModes: 'أوضاع الألوان',
    grayscale: 'تدرج الرمادي',
    invertColors: 'عكس الألوان',
    lowSaturation: 'تشبع منخفض',
    colorBlindFilter: 'فلتر عمى الألوان',
    none: 'بدون',
    redGreen: 'أحمر/أخضر',
    red: 'أحمر',
    blueYellow: 'أزرق/أصفر',
    visualOptions: 'خيارات بصرية',
    highContrast: 'تباين عالي',
    largeText: 'نص كبير',
    highlightLinks: 'تمييز الروابط',
    underlineLinks: 'تسطير الروابط',
    hideImages: 'إخفاء الصور',
    textOptions: 'خيارات النص',
    readableFont: 'خط مقروء',
    increaseLineSpacing: 'زيادة تباعد الأسطر',
    letterSpacing: 'تباعد الأحرف',
    textAlignment: 'محاذاة النص',
    navigationOptions: 'خيارات التنقل',
    largeCursor: 'مؤشر كبير',
    reduceMotion: 'تقليل الحركة',
    stopAnimations: 'إيقاف الرسوم المتحركة',
    resetToDefault: 'إعادة تعيين للافتراضي',
    needHelp: 'هل تحتاج للمساعدة؟',
    viewFullStatement: 'عرض بيان الوصول الكامل'
  },
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_services: 'Services',
    nav_projects: 'Projects',
    nav_contact: 'Contact',
    hero_title: 'A. Maale Hashahar',
    hero_subtitle: 'Leading Manpower for Construction - Service, Safety, and Reliability',
    hero_cta: 'Send CV',
    about_title: 'About Us',
    about_desc: 'A. Maale Hashahar provides professional manpower for the construction industry nationwide, strictly adhering to service, safety, and reliability standards.',
    services_title: 'Our Services',
    projects_title: 'Clients & Projects',
    why_us_title: 'Why Choose Us?',
    contact_title: 'Submit CV',
    contact_name: 'Full Name',
    contact_email: 'Email',
    contact_phone: 'Phone',
    contact_city: 'City',
    contact_cv: 'Resume (CV)',
    contact_submit: 'Submit',
    contact_info_title: 'Contact Info',
    footer_rights: '© 2025 A. Maale Hashahar Manpower Services Ltd.',
    
    // Accessibility
    access_title: 'Accessibility',
    accessibility: 'Accessibility',
    accessibilityTools: 'Accessibility Tools',
    customizeYourExperience: 'Customize your experience',
    textSize: 'Text Size',
    colorModes: 'Color Modes',
    grayscale: 'Grayscale',
    invertColors: 'Invert Colors',
    lowSaturation: 'Low Saturation',
    colorBlindFilter: 'Color Blind Filter',
    none: 'None',
    redGreen: 'Red/Green (Deuteranopia)',
    red: 'Red (Protanopia)',
    blueYellow: 'Blue/Yellow (Tritanopia)',
    visualOptions: 'Visual Options',
    highContrast: 'High Contrast',
    largeText: 'Large Text',
    highlightLinks: 'Highlight Links',
    underlineLinks: 'Underline Links',
    hideImages: 'Hide Images',
    textOptions: 'Text Options',
    readableFont: 'Readable Font',
    increaseLineSpacing: 'Increase Line Spacing',
    letterSpacing: 'Letter Spacing',
    textAlignment: 'Text Alignment',
    navigationOptions: 'Navigation Options',
    largeCursor: 'Large Cursor',
    reduceMotion: 'Reduce Motion',
    stopAnimations: 'Stop Animations',
    resetToDefault: 'Reset to Default',
    needHelp: 'Need help?',
    viewFullStatement: 'View Full Statement'
  },
};

export const SERVICES_LIST = [
  { icon: Users, label_he: 'עובדים כלליים', label_ar: 'عمال عامون', label_en: 'General Workers' },
  { icon: ShieldCheck, label_he: 'עוזרי בטיחות', label_ar: 'مساعدو أمان', label_en: 'Safety Assistants' },
  { icon: ClipboardList, label_he: 'מנהלי עבודה', label_ar: 'مديرو عمل', label_en: 'Site Managers' },
  { icon: HardHat, label_he: 'אתתים', label_ar: 'إشارات', label_en: 'Signalmen' },
  { icon: Forklift, label_he: 'נהגי מלגזה', label_ar: 'سائقي رافعات شوكية', label_en: 'Forklift Drivers' },
];

export const PROJECTS_LIST: ProjectItem[] = [
  {
    image: '/client-etz-hashaked.jpeg',
    name_en: 'Etz HaShaked Real Estate',
    name_he: 'עץ השקד נדל״ן',
    name_ar: 'إتس هشكيد للعقارات',
    location_en: 'Netanya',
    location_he: 'נתניה',
    location_ar: 'نتانيا',
    description_en: 'Residential building up to 32 floors',
    description_he: 'בניין מגורים עד 32 קומות',
    description_ar: 'مبنى سكني حتى 32 طابقًا',
  },
  {
    image: '/client-virtue.jpeg',
    name_en: 'Virtue Group',
    name_he: 'קבוצת וירטו',
    name_ar: 'مجموعة فيرتو',
    location_en: 'Ramat HaSharon',
    location_he: 'רמת השרון',
    location_ar: 'رمات هشارون',
    description_en: 'Residential building up to 7 floors',
    description_he: 'בניין מגורים עד 7 קומות',
    description_ar: 'مبنى سكني حتى 7 طوابق',
  },
  {
    image: '/client-gani-bar.png',
    name_en: 'Gani Bar',
    name_he: 'גני בר',
    name_ar: 'جاني بار',
    location_en: 'Eilat',
    location_he: 'אילת',
    location_ar: 'إيلات',
    description_en: 'Residential building up to 9 floors',
    description_he: 'בניין מגורים עד 9 קומות',
    description_ar: 'مبنى سكني حتى 9 طوابק',
  },
  {
    image: '/client-inadlan.jpeg',
    name_en: 'i-Nadlan',
    name_he: 'איי-נדל״ן',
    name_ar: 'آي-للعقارات',
    location_en: 'Eilat',
    location_he: 'אילת',
    location_ar: 'إيلات',
    description_en: 'Property Management & Construction',
    description_he: 'ניהול נכסים ובנייה',
    description_ar: 'إدارة الممتلكات والبناء',
  },
];

export const CONTACT_INFO = {
  name: 'Anwar Diab',
  phone: '053-4439990',
  email: '4439990@gmail.com',
  whatsapp: '972534439990',
  facebook: 'https://www.facebook.com/share/1GHpeg3cyf',
  instagram: 'https://www.instagram.com/a.maalehashahr',
  formAction: 'https://usebasin.com/f/74427cf34038'
};